### ISSUE TITLE
Organizer github access

### ISSUE THREAD

**Issue by knewter** [papers-we-love/remote-pwl#1]
Can the organizers get access to the repo?  We are:
- @knewter
- @cmeiklejohn
- @franzejr

Thanks!  I've got a commit ready to push that creates the initial README and updates the code-of-conduct.

**Comment by franzejr** [comment]
I cannot see `Settings`. It should be like this ?

**Comment by zeeshanlakhani** [comment]
pinging @hakutsuru

**Comment by knewter** [comment]
@hakutsuru sorry to keep pinging, just wanted to say that I saw in the other thread that we should have received an invitation to join the team, and sure enough it was hidden in my email.  @franzejr check for an email with the title 'hakutsuru invited you to papers-we-love/remote-pwl'.  I'm closing this issue for now.
